Add missing header for Qt 6 Q_PROPERTY
Q_PROPERTY need access to the class definition, not just a forward
declaration. Fails to build on Qt 6 with:

/usr/include/qt6/QtCore/qmetatype.h:1209:55: error:
static assertion failed: Pointer Meta Types must either point to
fully-defined types or be declared with Q_DECLARE_OPAQUE_POINTER(T *)